#! /usr/local/bin/python3
import sys
from shutil import copyfile
from os.path import exists
from subprocess import call
from onlinejudge.implementation.main import main as ojmain

if len(sys.argv) == 1:
    print(f"""
      - <num> setup :: setup y<num>.nim
      - <num> test :: try test
      - <num> <in.txt> :: try by in.txt
    """)
    exit()
num = sys.argv[1]
new_file = "y" + num + ".nim"
if len(sys.argv) == 2 or sys.argv[2] in ["setup", "start", "s"]:
    if not exists(new_file):
        copyfile("./template.nim", new_file)
    call(["code", new_file])
    exit()

if sys.argv[2] in ["dl", "download", "d"]:
    call(["rm", "-rf", "test"])
    ojmain(args=["dl", "https://yukicoder.me/problems/no/" + num])
    call(["./" + sys.argv[0], num, "test"])

if sys.argv[2] in ["test", "t", "tr"]:
    pre_code = ["nim", "c", "--hints:off", "--verbosity:0"]
    pro_code = ["--nimcache:./nimcache", new_file]
    if sys.argv[2] == "tr":
        retcode = call(pre_code + ["-d:release"] + pro_code)
    else:
        retcode = call(pre_code + pro_code)
    if retcode != 0:
        exit()
    call(["mv", "y" + num, "a.out"])
    ojmain(args=["test"])
