#! /usr/local/bin/python3
import sys
from shutil import copyfile
from os.path import exists
from subprocess import call
from onlinejudge.implementation.main import main as ojmain

# ./at 128 a
if len(sys.argv) == 2:
    print(f"""
      - <num> setup :: setup y<num>.nim
      - <num> test :: try test
      - <num> <in.txt> :: try by in.txt
    """)
    exit()
num = sys.argv[1]
ver = sys.argv[2]
new_file = ver + ".nim"

if sys.argv[3] in ["dl", "download", "d"]:
    call(["rm", "-rf", "test"])
    ojmain(args=["dl", "https://atcoder.jp/contests/abc" +
                 num+"/tasks/abc"+num+"_"+ver])
    call(["./" + sys.argv[0], num, ver, "test"])

if sys.argv[3] in ["test", "t", "tr"]:
    pre_code = ["nim", "c", "--hints:off", "--verbosity:0"]
    pro_code = ["--nimcache:./nimcache", new_file]
    if sys.argv[2] == "tr":
        retcode = call(pre_code + ["-d:release"] + pro_code)
    else:
        retcode = call(pre_code + pro_code)
    if retcode != 0:
        exit()
    call(["mv", ver, "a.out"])
    ojmain(args=["test"])
